name: Key Auto Update

on:
  schedule:
    - cron: '*/20 * * * *'  # Tenta ogni 5 minuti
  workflow_dispatch:      # <--- Questo ti permette di avviarlo a mano per test
  push:                   # <--- Questo lo avvia ogni volta che modifichi un file
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python update_key.py
